export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          telegram_id: string;
          username: string | null;
          timezone: string;
          home_chat_id: string | null;
          home_message_id: string | null;
          settings_json: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          telegram_id: string;
          username?: string | null;
          timezone?: string;
          home_chat_id?: string | null;
          home_message_id?: string | null;
          settings_json?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          telegram_id?: string;
          username?: string | null;
          timezone?: string;
          home_chat_id?: string | null;
          home_message_id?: string | null;
          settings_json?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      reminders: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          detail: string | null;
          next_run_at_utc: string | null;
          last_sent_at_utc: string | null;
          enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          detail?: string | null;
          next_run_at_utc?: string | null;
          last_sent_at_utc?: string | null;
          enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          detail?: string | null;
          next_run_at_utc?: string | null;
          last_sent_at_utc?: string | null;
          enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      daily_reports: {
        Row: {
          id: string;
          user_id: string;
          report_date: string;
          wake_time: string | null;
          weekday: string | null;
          routine_morning: boolean | null;
          routine_school: boolean | null;
          routine_taxi: boolean | null;
          routine_evening: boolean | null;
          routine_night: boolean | null;
          review_today_hours: number | null;
          preview_tomorrow_hours: number | null;
          homework_done: boolean | null;
          workout_morning: boolean | null;
          workout_night: boolean | null;
          pomodoro_3_count: number | null;
          pomodoro_2_count: number | null;
          pomodoro_1_count: number | null;
          city_library_hours: number | null;
          exam_school_questions: number | null;
          exam_maz_questions: number | null;
          exam_hesaban_questions: number | null;
          exam_physics_questions: number | null;
          exam_chemistry_questions: number | null;
          exam_geology_questions: number | null;
          exam_language_questions: number | null;
          exam_religion_questions: number | null;
          exam_arabic_questions: number | null;
          exam_farsi_questions: number | null;
          exam_philosophy_questions: number | null;
          exam_sociology_questions: number | null;
          exam_konkur_questions: number | null;
          non_academic_book_hours: number | null;
          non_academic_article_hours: number | null;
          non_academic_video_hours: number | null;
          non_academic_course_hours: number | null;
          english_content_hours: number | null;
          english_speaking_hours: number | null;
          english_class_hours: number | null;
          extra_skill_learning: boolean | null;
          extra_telegram_bot: boolean | null;
          extra_trading_strategy: boolean | null;
          organize_study_space: boolean | null;
          clean_room: boolean | null;
          plan_tomorrow: boolean | null;
          family_time_hours: number | null;
          planned_study_hours: number | null;
          planned_skills_hours: number | null;
          planned_misc_hours: number | null;
          streak_done: boolean | null;
          streak_days: number | null;
          xp_s: number | null;
          xp_study: number | null;
          xp_misc: number | null;
          xp_total: number | null;
          sleep_time: string | null;
          note: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          report_date: string;
          wake_time?: string | null;
          weekday?: string | null;
          routine_morning?: boolean | null;
          routine_school?: boolean | null;
          routine_taxi?: boolean | null;
          routine_evening?: boolean | null;
          routine_night?: boolean | null;
          review_today_hours?: number | null;
          preview_tomorrow_hours?: number | null;
          homework_done?: boolean | null;
          workout_morning?: boolean | null;
          workout_night?: boolean | null;
          pomodoro_3_count?: number | null;
          pomodoro_2_count?: number | null;
          pomodoro_1_count?: number | null;
          city_library_hours?: number | null;
          exam_school_questions?: number | null;
          exam_maz_questions?: number | null;
          exam_hesaban_questions?: number | null;
          exam_physics_questions?: number | null;
          exam_chemistry_questions?: number | null;
          exam_geology_questions?: number | null;
          exam_language_questions?: number | null;
          exam_religion_questions?: number | null;
          exam_arabic_questions?: number | null;
          exam_farsi_questions?: number | null;
          exam_philosophy_questions?: number | null;
          exam_sociology_questions?: number | null;
          exam_konkur_questions?: number | null;
          non_academic_book_hours?: number | null;
          non_academic_article_hours?: number | null;
          non_academic_video_hours?: number | null;
          non_academic_course_hours?: number | null;
          english_content_hours?: number | null;
          english_speaking_hours?: number | null;
          english_class_hours?: number | null;
          extra_skill_learning?: boolean | null;
          extra_telegram_bot?: boolean | null;
          extra_trading_strategy?: boolean | null;
          organize_study_space?: boolean | null;
          clean_room?: boolean | null;
          plan_tomorrow?: boolean | null;
          family_time_hours?: number | null;
          planned_study_hours?: number | null;
          planned_skills_hours?: number | null;
          planned_misc_hours?: number | null;
          streak_done?: boolean | null;
          streak_days?: number | null;
          xp_s?: number | null;
          xp_study?: number | null;
          xp_misc?: number | null;
          xp_total?: number | null;
          sleep_time?: string | null;
          note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          report_date?: string;
          wake_time?: string | null;
          weekday?: string | null;
          routine_morning?: boolean | null;
          routine_school?: boolean | null;
          routine_taxi?: boolean | null;
          routine_evening?: boolean | null;
          routine_night?: boolean | null;
          review_today_hours?: number | null;
          preview_tomorrow_hours?: number | null;
          homework_done?: boolean | null;
          workout_morning?: boolean | null;
          workout_night?: boolean | null;
          pomodoro_3_count?: number | null;
          pomodoro_2_count?: number | null;
          pomodoro_1_count?: number | null;
          city_library_hours?: number | null;
          exam_school_questions?: number | null;
          exam_maz_questions?: number | null;
          exam_hesaban_questions?: number | null;
          exam_physics_questions?: number | null;
          exam_chemistry_questions?: number | null;
          exam_geology_questions?: number | null;
          exam_language_questions?: number | null;
          exam_religion_questions?: number | null;
          exam_arabic_questions?: number | null;
          exam_farsi_questions?: number | null;
          exam_philosophy_questions?: number | null;
          exam_sociology_questions?: number | null;
          exam_konkur_questions?: number | null;
          non_academic_book_hours?: number | null;
          non_academic_article_hours?: number | null;
          non_academic_video_hours?: number | null;
          non_academic_course_hours?: number | null;
          english_content_hours?: number | null;
          english_speaking_hours?: number | null;
          english_class_hours?: number | null;
          extra_skill_learning?: boolean | null;
          extra_telegram_bot?: boolean | null;
          extra_trading_strategy?: boolean | null;
          organize_study_space?: boolean | null;
          clean_room?: boolean | null;
          plan_tomorrow?: boolean | null;
          family_time_hours?: number | null;
          planned_study_hours?: number | null;
          planned_skills_hours?: number | null;
          planned_misc_hours?: number | null;
          streak_done?: boolean | null;
          streak_days?: number | null;
          xp_s?: number | null;
          xp_study?: number | null;
          xp_misc?: number | null;
          xp_total?: number | null;
          sleep_time?: string | null;
          note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};

export type ReminderRow = Database['public']['Tables']['reminders']['Row'];
export type DailyReportRow = Database['public']['Tables']['daily_reports']['Row'];
export type DailyReportInsert = Database['public']['Tables']['daily_reports']['Insert'];
export type DailyReportUpdate = Database['public']['Tables']['daily_reports']['Update'];
