export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          telegram_id: string;
          username: string | null;
          timezone: string;
          home_chat_id: string | null;
          home_message_id: string | null;
          settings_json: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          telegram_id: string;
          username?: string | null;
          timezone?: string;
          home_chat_id?: string | null;
          home_message_id?: string | null;
          settings_json?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          telegram_id?: string;
          username?: string | null;
          timezone?: string;
          home_chat_id?: string | null;
          home_message_id?: string | null;
          settings_json?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      reminders: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          detail: string | null;
          next_run_at_utc: string | null;
          last_sent_at_utc: string | null;
          enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          detail?: string | null;
          next_run_at_utc?: string | null;
          last_sent_at_utc?: string | null;
          enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          detail?: string | null;
          next_run_at_utc?: string | null;
          last_sent_at_utc?: string | null;
          enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      daily_reports: {
        Row: {
          id: string;
          user_id: string;
          report_date: string;
          weekday: string | null;
          gym: boolean | null;
          running: boolean | null;
          studying: boolean | null;
          sleep_hours: number | null;
          routine_morning: boolean | null;
          routine_language: boolean | null;
          routine_meditation: boolean | null;
          routine_mobility: boolean | null;
          routine_english: boolean | null;
          routine_learning: boolean | null;
          work_small_1_pomodoro: boolean | null;
          work_big_3_pomodoro: boolean | null;
          rest: boolean | null;
          citylib_time_hours: number | null;
          citylib_book_hours: number | null;
          citylib_notes_hours: number | null;
          citylib_programming_hours: number | null;
          citylib_tests_hours: number | null;
          citylib_school_hours: number | null;
          strengths: string | null;
          weaknesses: string | null;
          weakness_reasons: string | null;
          solutions: string | null;
          daily_cost: number | null;
          cost_reason: string | null;
          supp_creatine: boolean | null;
          supp_zinc: boolean | null;
          supp_omega3: boolean | null;
          sleep_time_local: string | null;
          last_caffeine: boolean | null;
          burned_calories: number | null;
          routine_night: boolean | null;
          routine_evening: boolean | null;
          diet_ok: boolean | null;
          web_browsing: boolean | null;
          today_result: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          report_date: string;
          weekday?: string | null;
          gym?: boolean | null;
          running?: boolean | null;
          studying?: boolean | null;
          sleep_hours?: number | null;
          routine_morning?: boolean | null;
          routine_language?: boolean | null;
          routine_meditation?: boolean | null;
          routine_mobility?: boolean | null;
          routine_english?: boolean | null;
          routine_learning?: boolean | null;
          work_small_1_pomodoro?: boolean | null;
          work_big_3_pomodoro?: boolean | null;
          rest?: boolean | null;
          citylib_time_hours?: number | null;
          citylib_book_hours?: number | null;
          citylib_notes_hours?: number | null;
          citylib_programming_hours?: number | null;
          citylib_tests_hours?: number | null;
          citylib_school_hours?: number | null;
          strengths?: string | null;
          weaknesses?: string | null;
          weakness_reasons?: string | null;
          solutions?: string | null;
          daily_cost?: number | null;
          cost_reason?: string | null;
          supp_creatine?: boolean | null;
          supp_zinc?: boolean | null;
          supp_omega3?: boolean | null;
          sleep_time_local?: string | null;
          last_caffeine?: boolean | null;
          burned_calories?: number | null;
          routine_night?: boolean | null;
          routine_evening?: boolean | null;
          diet_ok?: boolean | null;
          web_browsing?: boolean | null;
          today_result?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          report_date?: string;
          weekday?: string | null;
          gym?: boolean | null;
          running?: boolean | null;
          studying?: boolean | null;
          sleep_hours?: number | null;
          routine_morning?: boolean | null;
          routine_language?: boolean | null;
          routine_meditation?: boolean | null;
          routine_mobility?: boolean | null;
          routine_english?: boolean | null;
          routine_learning?: boolean | null;
          work_small_1_pomodoro?: boolean | null;
          work_big_3_pomodoro?: boolean | null;
          rest?: boolean | null;
          citylib_time_hours?: number | null;
          citylib_book_hours?: number | null;
          citylib_notes_hours?: number | null;
          citylib_programming_hours?: number | null;
          citylib_tests_hours?: number | null;
          citylib_school_hours?: number | null;
          strengths?: string | null;
          weaknesses?: string | null;
          weakness_reasons?: string | null;
          solutions?: string | null;
          daily_cost?: number | null;
          cost_reason?: string | null;
          supp_creatine?: boolean | null;
          supp_zinc?: boolean | null;
          supp_omega3?: boolean | null;
          sleep_time_local?: string | null;
          last_caffeine?: boolean | null;
          burned_calories?: number | null;
          routine_night?: boolean | null;
          routine_evening?: boolean | null;
          diet_ok?: boolean | null;
          web_browsing?: boolean | null;
          today_result?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};

export type ReminderRow = Database['public']['Tables']['reminders']['Row'];
export type DailyReportRow = Database['public']['Tables']['daily_reports']['Row'];
